name: publish
on: 
  push:
    branches: 
      - main
jobs: 
  publish-to-pages:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-pandoc@master
        with:
          pandoc-version: '2.14.2'
      - run: >-
          for f in ./pages/*.md; do 
            OUTPUT=output/$(basename $f .md).html
            pandoc -s --template=./template.html --output=$OUTPUT $f
          done
      - uses: JamesIves/github-pages-deploy-action@v4.2.3 
        with: 
          branch: gh-pages
          folder: output
