name: publish
on: 
  push:
    branches: 
      - main
jobs: 
  publish-to-pages:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@master
      - run: mkdir -p output/css
      - uses: r-lib/actions/setup-pandoc@master
        with:
          pandoc-version: '2.14.2'
      - name: generate index.html 
        run: |
          echo "---
title: Table of Contents
---

" > toc.md
          for f in ./pages/*.md; do
            TITLE=$(basename "$f" .md | awk '{$1=$2=""; print $0}' | xargs)
            PATH=$(basename "$f" .md | awk '{print $1}').html
            echo "$TITLE -> $PATH"
            echo "[$TITLE]($PATH)\n" >> toc.md
          done
          /usr/bin/cat toc.md
          /usr/bin/pandoc -s --template=./templates/tableofcontents.html --output="output/index.html" toc.md
      - name: generate html files
        run: |
          for f in ./pages/*.md; do 
            OUTPUT=output/$(basename "$f" .md | awk '{print $1}').html
            echo "$f > $OUTPUT"
            /usr/bin/pandoc -s --template=./templates/blogpost.html --output="$OUTPUT" "$f"
          done
      - run: cp ./styling/style.css ./output/css/style.css
      - uses: JamesIves/github-pages-deploy-action@v4.2.3 
        with: 
          branch: gh-pages
          folder: output
