name: publish
on: 
  push:
    branches: 
      - main
jobs: 
  publish-to-pages:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@master
      - name: create files list
        id: files_list
        run: |
          mkdir output
          echo "::set-output name=files::$(printf '"%s" ' ./pages/*.md)"
      - uses: docker://pandoc/core:2.14
        with:
          args: >-
            --standalone
            --output=output/result.html ${{ steps.files_list.outputs.files }}
            --template=template.html
      - uses: actions/upload-artifact@master
        with: 
          name: output
          path: output
